[build]
  publish = "dist/public"
  command = "node scripts/build-blog-data.js && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
